services:
  - type: web
    name: microservice-config
    env: docker
    rootDir: Backend-SpringMicroservices/microservice-config
    dockerfilePath: Backend-SpringMicroservices/microservice-config/Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: microservice-eureka
    env: docker
    rootDir: Backend-SpringMicroservices/microservice-eureka
    dockerfilePath: Backend-SpringMicroservices/microservice-eureka/Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: microservice-gateway
    env: docker
    rootDir: Backend-SpringMicroservices/microservice-gateway
    dockerfilePath: Backend-SpringMicroservices/microservice-gateway/Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: microservice-auth
    env: docker
    rootDir: Backend-SpringMicroservices/microservice-auth
    dockerfilePath: Backend-SpringMicroservices/microservice-auth/Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: microservice-course
    env: docker
    rootDir: Backend-SpringMicroservices/microservice-course
    dockerfilePath: Backend-SpringMicroservices/microservice-course/Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: microservice-report
    env: docker
    rootDir: Backend-SpringMicroservices/microservice-report
    dockerfilePath: Backend-SpringMicroservices/microservice-report/Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: microservice-student
    env: docker
    rootDir: Backend-SpringMicroservices/microservice-student
    dockerfilePath: Backend-SpringMicroservices/microservice-student/Dockerfile
    plan: free
    autoDeploy: true

  - type: web
    name: frontend-angular
    env: static
    rootDir: Frontend-proyecto-microservicios
    buildCommand: npm install && npm run build --prod
    staticPublishPath: dist
    autoDeploy: true
