server:
  port: ${PORT:8080}

spring:
  application:
    name: micro-service-eureka
  cloud:
    config:
      enabled: false   # Eureka NO usa Config Server

eureka:
  client:
    register-with-eureka: false   # No se registra a s√≠ mismo
    fetch-registry: false