server:
  port: 8888

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/carta87/Microservicios-integrados-basic-Render
          search-paths: config
          default-label: main