server:
  port: ${PORT:8888}

spring:
  application:
    name: microservice-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/carta87/configuraciones-microservicios
          search-paths: configurations
          default-label: render-basic